config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/about', to: 'pages#about'
  devise_for :users
  devise_scope :users do
    resources :users, only: [:show]    
  end
  resources :topics do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates_presence_of :user_id, :topic_id
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  validates_presence_of :title, :description, :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :sch_id, :full_name 
  validates :sch_id, uniqueness: true
  validates_length_of :sch_id, is: 13
  validates :full_name, length: { maximum: 100 }

  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

 	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :sch_id])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :sch_id])
  end

  def render_404
    respond_to do |format|
      format.html do
        render file: Rails.root.join("public", "404"), layout: false, status: "404"
      end
      format.any { head :not_found }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  
  # def new
  #   @topic = Topic.new
  # end

  # def index
  #   @topics = Topic.all
  # end

  def show; end

  def edit; end

  def create
    @topic = current_user.topics.build(topic_params)
    respond_to do |format|
      if @topic.save
        # redirect_back(fallback_location: fallback_location) 
        format.js { render js: "Materialize.toast('Topic created successfully!', 3000); location.reload();"}
      else
        format.js { render js: "Materialize.toast('Unable to create topic!', 3000);"}
      end
    end
  end

  def update; end

  def destroy; end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: :show

  def show
    @topic = Topic.new
    @user_topics = @user.topics
    # @comments = 
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VVU Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
  <%= render 'shared/nav' %>
    <%= yield %>
    <%= render 'shared/footer' %>

  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
<style>
  .icon-style {
    position: absolute;
    right: 10px;
    top: 10px;
    font-size: 20px;
    color: white;
    cursor: pointer;
  }
</style>

<div class="row" id="alert_box">
  <div class="col s12 m12">
    <div class="card red darken-1">
      <div class="row">
        <div class="col s12 m10">
          <div class="card-content white-text">
            <span class="flow-text"> <%= pluralize(object.errors.count, "error") %> prohibited this form from being sent.</span>
            <ul>
              <% object.errors.full_messages.each do |msg| %>
                <li>
                  <span class="flow-text"> <%= msg %> </span>
                </li>
              <% end %>
              
            </ul>
          </div>
        </div>
        <div class="col s12 m2">
          <i class="fa fa-times icon_style" id="alert_close" arial-hidden="true"></i>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('#alert_close').click(function(){
    $('#alert_box').fadeOut('slow', function(){

    });
  });
</script>
 
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>

<div id="card-alert" class="card red">
  <div class="card-content white-text">
    <p><%= message %></p>
  </div>
  <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
<% end %>

app/views/shared/_footer.html.erb
  <footer class="page-footer blue-grey darken-3">
    <div class="footer-copyright">
        <div class="container">
        <div class="row">
          <div class="col s12">
            <center>
             &copy; 2017. Made by <a class="orange-text text-lighten-3" href="https://polymathwhiz.github.io" target="_blank"> <b>PolymathWhiz</b></a>
            </center>
          </div>
        </div>
       
        </div>
    </div>
  </footer>

app/views/shared/_nav.html.erb
 <nav class="blue-grey darken-3" role="navigation">
    <div class="nav-wrapper container">
      <%= link_to 'Slick', root_path, class: 'brand-logo', id: 'logo-container' %>
      <ul class="right hide-on-med-and-down">
       <% if user_signed_in? %>
        <li>
            <%= link_to 'Profile', user_path(current_user) %>
        </li>
        <li>
          <%= link_to 'Settings', edit_user_registration_path %>
        </li>

        <li>
          <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow" >Logout </a>
        </li>
       <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>

        <li>
          <%= link_to 'Signup', new_user_registration_path %>
        </li>
       <% end %>
       
      </ul>

      <ul id="nav-mobile" class="side-nav">
       <% if user_signed_in? %>
        <li>
            <%= link_to 'Profile', user_path(current_user) %>
        </li>
         <li>
          <%= link_to 'Settings', edit_user_registration_path %>
        </li>

        <li>
          <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow" >Logout </a>
        </li>
       <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>

        <li>
          <%= link_to 'Signup', new_user_registration_path %>
        </li>
       <% end %>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m12 l12">
      <h1 class="header"><%= @topic.title %></h1> 
      <div class="divider"></div>
    </div>
  </div>
  <div class="row">
    <div class="col s9 m9 l9">
      <%= @topic.description %>
    </div>
    <div class="col m3">
      <span class="right hide-on-med-and-down">Posted: <%= @topic.created_at.to_date.to_s(:long) %></span> <br>
      <span class="right">By <%= @topic.user.full_name%></span>
    </div>
  </div>
</div>

<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>

app/views/users/show.html.erb
   <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12" style="margin-top: 20px;">
                    <center>
                        <%= image_tag 'def-img', class: 'circle responsive-img' %>
                        <p class="dash-name">Welcome, <%= @user.full_name%>!</p>

                        <div class="">
                            <p>Privilege: <span>Admin</span></p>
                            <a href="#topicmodal" class="btn flat modal-trigger" style="margin-bottom: 40px;">Create Topic</a>
                        </div>
                    </center>
                </div>
            </div>
        </div>
    </div>

    <div class="section"></div>
    <div class="section"></div>

  <div class="container">
    <div class="row">
      <div class="col s12">
        <h5 class="base_color">Your recent topics</h5>
        <div class="divider"></div>
      </div>
    </div>

  <div class="row">
    <% @user_topics.each do |topic| %>
      <div class="col s12 m4">
        <div class="card darken-1">
          <div class="card-content black-text">
            <h2 class="card-title truncate" title="<%= topic.title%>"><%= topic.title %></h2>
            <div class="divider"></div>
            <p style="margin-top: 30px;"><%= topic.description %></p>
          </div>
          <div class="card-action">
            <span><%= pluralize(@comments, "comment")%></span>
            <%= link_to 'View', topic_path(topic), class: 'right' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>


<!-- Modal -->
<%= form_for(@topic, url: topics_path, remote:true,  html:{ 'data-parsley-validate' => '' }) do |f| %>
<div id="topicmodal" class="modal">
  <div class="modal-content">
    <h5>
      New Topic
    </h5>
    <div class="divider"></div>
    
        <div class='row'>
          <div class='input-field col s12'>
            <%= f.text_field :title, required: true, 'data-parsley-minlength': '1', 'data-parsley-maxlength': '140','data-parsley-trigger': 'blur'  %>
            <label for='title'>Title</label>
          </div>
        </div>

        <div class='row'>
          <div class='input-field col s12'>
            <%= f.text_area :description, class: 'materialize-textarea', placeholder: 'Write something nice...', required: true, 'data-parsley-minlength': '1', 'data-parsley-maxlength': '140','data-parsley-trigger': 'blur'
             %>
            <label for='description'>Description</label>
          </div>
        </div>

  </div>
  <div class="modal-footer">
    <a href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
    <%= f.submit "Post", class: 'modal-action waves-effect waves-light btn-flat' %>
  </div>
</div>

<% end %>

<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>
<div class="section"></div>